"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-05-06 22:40:05.307230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasting_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_observed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observed_reason', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ix_users_observed_partial is a partial index — created manually below via op.execute
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_snapshot', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ix_audit_action_time_failed is a partial index — created manually below via op.execute
    op.create_index('ix_audit_user_time', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('grind_type', sa.String(length=40), nullable=True),
    sa.Column('grind_range', sa.String(length=80), nullable=True),
    sa.Column('grind_unit', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roasters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('beans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roaster_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('origin_country', sa.String(length=80), nullable=False),
    sa.Column('origin_region', sa.String(length=80), nullable=True),
    sa.Column('process', sa.String(length=40), nullable=False),
    sa.Column('roast_level', sa.String(length=40), nullable=False),
    sa.Column('variety', sa.String(length=80), nullable=True),
    sa.Column('elevation_m', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roaster_id'], ['roasters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beans_roaster', 'beans', ['roaster_id'], unique=False)
    op.create_index('ix_beans_user_name', 'beans', ['user_id', 'name'], unique=False)
    op.create_table('bean_tasting_notes',
    sa.Column('bean_id', sa.UUID(), nullable=False),
    sa.Column('tasting_note_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tasting_note_id'], ['tasting_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bean_id', 'tasting_note_id')
    )
    op.create_table('brewlogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bean_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('grinder_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grind_setting', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('dose_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('water_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('water_temp_c', sa.Integer(), nullable=False),
    sa.Column('brew_time_s', sa.Integer(), nullable=False),
    sa.Column('yield_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('taste_result', sa.String(length=40), nullable=True),
    sa.Column('grind_adjustment', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_brewlogs_rating_range'),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grinder_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brewlogs_bean', 'brewlogs', ['bean_id'], unique=False)
    op.create_index('ix_brewlogs_equipment', 'brewlogs', ['equipment_id'], unique=False)
    op.create_index('ix_brewlogs_user_date', 'brewlogs', ['user_id', 'date'], unique=False)
    op.create_table('brewlog_tasting_notes',
    sa.Column('brewlog_id', sa.UUID(), nullable=False),
    sa.Column('tasting_note_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brewlog_id'], ['brewlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tasting_note_id'], ['tasting_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brewlog_id', 'tasting_note_id')
    )
    # ### end Alembic commands ###

    # Partial index — observed users hot list
    op.execute(
        "CREATE INDEX ix_users_observed_partial ON users (id) WHERE is_observed = true"
    )

    # Partial index — failed/denied audit rows for detection windows
    op.execute(
        "CREATE INDEX ix_audit_action_time_failed ON audit_log (action, created_at DESC) "
        "WHERE status IN ('FAIL','DENIED')"
    )

    # Detection stored procedure
    op.execute("""
    CREATE OR REPLACE FUNCTION detect_malicious(p_user_id UUID)
    RETURNS VOID AS $$
    DECLARE
      c_failed_login INT;
      c_perm_denied  INT;
      c_mass_mutate  INT;
      c_mass_delete  INT;
      v_reason       TEXT := NULL;
    BEGIN
      IF p_user_id IS NULL OR
         EXISTS (SELECT 1 FROM users WHERE id = p_user_id AND is_observed)
      THEN
        RETURN;
      END IF;

      SELECT count(*) INTO c_failed_login FROM audit_log
       WHERE user_id = p_user_id AND action = 'LOGIN_FAIL'
         AND created_at > now() - interval '5 minutes';
      IF c_failed_login >= 5 THEN
        v_reason := format('failed-login-burst (%s in 5min)', c_failed_login);
      END IF;

      IF v_reason IS NULL THEN
        SELECT count(*) INTO c_perm_denied FROM audit_log
         WHERE user_id = p_user_id AND status = 'DENIED'
           AND created_at > now() - interval '5 minutes';
        IF c_perm_denied >= 5 THEN
          v_reason := format('permission-denied-burst (%s in 5min)', c_perm_denied);
        END IF;
      END IF;

      IF v_reason IS NULL THEN
        SELECT count(*) INTO c_mass_mutate FROM audit_log
         WHERE user_id = p_user_id AND status = 'OK'
           AND action ~ '_(CREATE|UPDATE|DELETE)$'
           AND created_at > now() - interval '60 seconds';
        IF c_mass_mutate >= 20 THEN
          v_reason := format('mass-mutation-burst (%s in 60s)', c_mass_mutate);
        END IF;
      END IF;

      IF v_reason IS NULL THEN
        SELECT count(*) INTO c_mass_delete FROM audit_log
         WHERE user_id = p_user_id AND status = 'OK'
           AND action LIKE '%_DELETE'
           AND created_at > now() - interval '60 seconds';
        IF c_mass_delete >= 10 THEN
          v_reason := format('mass-delete-burst (%s in 60s)', c_mass_delete);
        END IF;
      END IF;

      IF v_reason IS NOT NULL THEN
        UPDATE users SET is_observed = true,
                         observed_reason = v_reason,
                         observed_at = now()
        WHERE id = p_user_id;

        INSERT INTO audit_log(user_id, role_snapshot, action, status, metadata)
        VALUES (p_user_id, NULL, 'OBSERVED_AUTO', 'SYSTEM',
                jsonb_build_object('reason', v_reason));
      END IF;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # Trigger function — fires detection unless the row is itself a SYSTEM row
    op.execute("""
    CREATE OR REPLACE FUNCTION audit_log_after_insert_fn()
    RETURNS TRIGGER AS $$
    BEGIN
      IF NEW.status <> 'SYSTEM' AND NEW.user_id IS NOT NULL THEN
        PERFORM detect_malicious(NEW.user_id);
      END IF;
      RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER audit_log_after_insert
    AFTER INSERT ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_after_insert_fn();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_after_insert ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_after_insert_fn()")
    op.execute("DROP FUNCTION IF EXISTS detect_malicious(UUID)")
    op.execute("DROP INDEX IF EXISTS ix_audit_action_time_failed")
    op.execute("DROP INDEX IF EXISTS ix_users_observed_partial")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brewlog_tasting_notes')
    op.drop_index('ix_brewlogs_user_date', table_name='brewlogs')
    op.drop_index('ix_brewlogs_equipment', table_name='brewlogs')
    op.drop_index('ix_brewlogs_bean', table_name='brewlogs')
    op.drop_table('brewlogs')
    op.drop_table('bean_tasting_notes')
    op.drop_index('ix_beans_user_name', table_name='beans')
    op.drop_index('ix_beans_roaster', table_name='beans')
    op.drop_table('beans')
    op.drop_table('user_roles')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_table('roasters')
    op.drop_table('equipment')
    op.drop_index('ix_audit_user_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('tasting_notes')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
